[font]
normal = { family = "VictorMono Nerd Font", style = "Medium" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Oblique" }
size = 14.0

[shell]
program = "/usr/bin/zsh"
